# Enable all methods on nodes.
resources:
  entity:node:
    GET:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
    POST:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
    PATCH:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth

# Multiple formats and multiple authentication providers can be defined for a
# resource:
#
# resources:
#   entity:node:
#     GET:
#       supported_formats:
#         - json
#         - hal_json
#         - xml
#       supported_auth:
#         - cookie
#         - basic_auth
#
# hal_json is the only format supported for POST and PATCH methods.
#
# The full documentation is located at
# https://drupal.org/documentation/modules/rest
